spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true

h2:
  console:
    enabled: true
    path: /h2-console